package IU;

import BaseDeDatos.Materia;

import javax.swing.*;

/**
 * @author FedeSSD
 */
public class VistaEventos extends javax.swing.JPanel {
    VistaPrincipal vistaPrincipal;

    /**
     * @brief constructor de clase
     * @param vp vista prioncipal
     */
    DefaultListModel modeloLista = new DefaultListModel();


    public VistaEventos(VistaPrincipal vp) {
        //asigno la vita principal
        this.vistaPrincipal = vp;

        //inicio componentes
        initComponents();

        listaEventos.setModel(modeloLista);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VistaEventos = new javax.swing.JLabel();
        AgregarVariante = new javax.swing.JButton();
        EliminarEventos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEventos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(280, 280));

        VistaEventos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VistaEventos.setText("Eventos");

        AgregarVariante.setIcon(new javax.swing.ImageIcon("C:\\ingsoft\\Gendat\\icons\\icons8-add-64.png")); // NOI18N
        AgregarVariante.setMaximumSize(new java.awt.Dimension(130, 25));
        AgregarVariante.setMinimumSize(new java.awt.Dimension(130, 25));
        AgregarVariante.setPreferredSize(new java.awt.Dimension(135, 25));
        AgregarVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarVarianteActionPerformed(evt);
            }
        });

        EliminarEventos.setIcon(new javax.swing.ImageIcon("C:\\ingsoft\\Gendat\\icons\\icons8-delete-64.png")); // NOI18N
        EliminarEventos.setMaximumSize(new java.awt.Dimension(125, 25));
        EliminarEventos.setMinimumSize(new java.awt.Dimension(125, 25));
        EliminarEventos.setPreferredSize(new java.awt.Dimension(125, 25));
        EliminarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEventosActionPerformed(evt);
            }
        });

        listaEventos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "sdvcsdv", "sdvsdvsf" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaEventos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaEventos.setToolTipText("");
        jScrollPane1.setViewportView(listaEventos);
        listaEventos.getAccessibleContext().setAccessibleName("");

        jLabel1.setText("Agregar Variante");

        jLabel2.setText("Eliminar Evento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(VistaEventos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(AgregarVariante, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EliminarEventos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VistaEventos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarVariante, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(EliminarEventos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    //-------------ACCIONES DE BOTONES----------
    //******************************************
    private void AgregarVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarVarianteActionPerformed
        boolean seleccion;
        seleccion = listaEventos.isSelectionEmpty();
        if(seleccion){
            JOptionPane.showMessageDialog(null, "No selecciono ningun evento para agregar variantes.");
        }
        else {
            boolean materia;
            int index = listaEventos.getSelectedIndex();
            String nombreEvento = modeloLista.get(index).toString();
            materia = this.vistaPrincipal.getUsuarioSeleccionado().getEvento(nombreEvento) instanceof Materia;
            vistaPrincipal.vistaVariante.setVisible(true);
            if (materia) {
                vistaPrincipal.vistaVariante.agregarComision();
            } else {
                vistaPrincipal.vistaVariante.agregarOpcion();
            }
        }
    }//GEN-LAST:event_AgregarVarianteActionPerformed

    private void EliminarEventosActionPerformed(java.awt.event.ActionEvent evt) {                                                
        boolean seleccion = listaEventos.isSelectionEmpty();
        if (seleccion) {
            JOptionPane.showMessageDialog(null, "No selecciono ningun evento a eliminar.");
        } else {
            int index = listaEventos.getSelectedIndex();
            String nombreEvento = modeloLista.get(index).toString();
            eliminarDeLista(nombreEvento);
        }
    }

    //-------------METODOS PARTICULARES---------
    //******************************************

    /**
     * Agrego a la lista el elemento del evento
     *
     * @param nombreEvento
     */
    public void agregarALista(String nombreEvento) {
        modeloLista.addElement(nombreEvento);
    }

    /**
     * Elimino el elemento seleccionado de la lista
     *
     * @param nombreEvento
     */
    public void eliminarDeLista(String nombreEvento) {
        this.vistaPrincipal.getUsuarioSeleccionado().quitEvento(nombreEvento);
        modeloLista.removeElement(nombreEvento);
    }

    public void vaciarLista() {
        modeloLista.clear();
    }


    //-------------INTOCABLE-------------------
    //******************************************
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarVariante;
    private javax.swing.JButton EliminarEventos;
    private javax.swing.JLabel VistaEventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList<String> listaEventos;
    // End of variables declaration//GEN-END:variables
}






