/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

/**
 *
 * @author marco
 */
public class VistaVariante extends javax.swing.JFrame {
    VistaPrincipal vistaPrincipal;

    /**
     * Creates new form VistaVariante
     */
    public VistaVariante(VistaPrincipal vp) {
        initComponents();
        this.vistaPrincipal = vp;
        ComisionFrame.setVisible(false);
        OpcionFrame.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComisionFrame = new javax.swing.JInternalFrame();
        ProfeField = new javax.swing.JTextField();
        NumeroField = new javax.swing.JTextField();
        AulaField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DiaField = new javax.swing.JTextField();
        HoraInicioFIeld = new javax.swing.JTextField();
        MinutoInicioField = new javax.swing.JTextField();
        HoraFinField = new javax.swing.JTextField();
        MinutoFinField = new javax.swing.JTextField();
        BoxPrioM = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        OpcionFrame = new javax.swing.JInternalFrame();
        LugarField = new javax.swing.JTextField();
        DiaFieldOp = new javax.swing.JTextField();
        MinutoInicioFIeldOp = new javax.swing.JTextField();
        HoraInicioFieldOp = new javax.swing.JTextField();
        MinutoFinFieldOp = new javax.swing.JTextField();
        HoraFinFieldOp = new javax.swing.JTextField();
        BoxPiroO = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        BoxComision = new javax.swing.JCheckBox();
        BoxOpcion = new javax.swing.JCheckBox();
        BtGuardar = new javax.swing.JButton();
        BtAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        ComisionFrame.setVisible(true);

        AulaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AulaFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Profesor");

        jLabel2.setText("Numero");

        DiaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaFieldActionPerformed(evt);
            }
        });

        MinutoInicioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinutoInicioFieldActionPerformed(evt);
            }
        });

        BoxPrioM.setText("Prioritaria");
        BoxPrioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxPrioMActionPerformed(evt);
            }
        });

        jLabel3.setText("Aula");

        jLabel4.setText("Dia");

        jLabel5.setText("Hora/Minuto Inicio");

        jLabel7.setText("Hora/Minuto Fin");

        jLabel6.setText(":");

        jLabel16.setText(":");

        javax.swing.GroupLayout ComisionFrameLayout = new javax.swing.GroupLayout(ComisionFrame.getContentPane());
        ComisionFrame.getContentPane().setLayout(ComisionFrameLayout);
        ComisionFrameLayout.setHorizontalGroup(
            ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComisionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComisionFrameLayout.createSequentialGroup()
                        .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ComisionFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(HoraFinField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HoraInicioFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MinutoInicioField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MinutoFinField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7))
                            .addGroup(ComisionFrameLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(DiaField))))
                    .addGroup(ComisionFrameLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(BoxPrioM)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComisionFrameLayout.createSequentialGroup()
                        .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AulaField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(NumeroField)
                            .addComponent(ProfeField))))
                .addContainerGap())
        );
        ComisionFrameLayout.setVerticalGroup(
            ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComisionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProfeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AulaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraInicioFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(MinutoInicioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(ComisionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraFinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinutoFinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(BoxPrioM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OpcionFrame.setVisible(true);

        LugarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarFieldActionPerformed(evt);
            }
        });

        MinutoInicioFIeldOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinutoInicioFIeldOpActionPerformed(evt);
            }
        });

        HoraFinFieldOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoraFinFieldOpActionPerformed(evt);
            }
        });

        BoxPiroO.setText("Prioritaria");

        jLabel9.setText("Lugar");

        jLabel10.setText("Dia");

        jLabel13.setText("Hora/Minuto Inicio");

        jLabel15.setText("Hora/Minuto Fin");

        jLabel8.setText("  : ");

        jLabel17.setText("  : ");

        javax.swing.GroupLayout OpcionFrameLayout = new javax.swing.GroupLayout(OpcionFrame.getContentPane());
        OpcionFrame.getContentPane().setLayout(OpcionFrameLayout);
        OpcionFrameLayout.setHorizontalGroup(
            OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionFrameLayout.createSequentialGroup()
                        .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OpcionFrameLayout.createSequentialGroup()
                                .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(HoraInicioFieldOp, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                    .addComponent(HoraFinFieldOp)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionFrameLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BoxPiroO)
                                .addGap(18, 18, 18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OpcionFrameLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MinutoFinFieldOp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OpcionFrameLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MinutoInicioFIeldOp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpcionFrameLayout.createSequentialGroup()
                        .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LugarField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(DiaFieldOp))))
                .addContainerGap())
        );
        OpcionFrameLayout.setVerticalGroup(
            OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionFrameLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(LugarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DiaFieldOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(HoraInicioFieldOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(MinutoInicioFIeldOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OpcionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinutoFinFieldOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(HoraFinFieldOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(31, 31, 31)
                .addComponent(BoxPiroO)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        BoxComision.setText("Comision");
        BoxComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxComisionActionPerformed(evt);
            }
        });

        BoxOpcion.setText("Opcion");
        BoxOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxOpcionActionPerformed(evt);
            }
        });

        BtGuardar.setText("Guardar Variante");
        BtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarActionPerformed(evt);
            }
        });

        BtAtras.setText("Atras");
        BtAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComisionFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OpcionFrame))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(BoxComision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoxOpcion)
                        .addGap(67, 67, 67)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxComision)
                    .addComponent(BoxOpcion))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComisionFrame)
                    .addComponent(OpcionFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(BtAtras))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxComisionActionPerformed

        if (BoxComision.isSelected()){
            ComisionFrame.setVisible(true);
            BoxOpcion.setSelected(false);
            OpcionFrame.setVisible(false);
        }
        else{
            ComisionFrame.setVisible(false);
        }
    }//GEN-LAST:event_BoxComisionActionPerformed

    private void BtAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAtrasActionPerformed
        vistaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtAtrasActionPerformed

    private void MinutoInicioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinutoInicioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinutoInicioFieldActionPerformed

    private void BoxPrioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxPrioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxPrioMActionPerformed

    private void HoraFinFieldOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoraFinFieldOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoraFinFieldOpActionPerformed

    private void MinutoInicioFIeldOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinutoInicioFIeldOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinutoInicioFIeldOpActionPerformed

    private void LugarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarFieldActionPerformed

    private void BtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtGuardarActionPerformed

    private void AulaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AulaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AulaFieldActionPerformed

    private void DiaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaFieldActionPerformed

    private void BoxOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxOpcionActionPerformed
        // TODO add your handling code here:
        if(BoxOpcion.isSelected()){
            OpcionFrame.setVisible(true);
            BoxComision.setSelected(false);
            ComisionFrame.setVisible(false); 
        }
         else{
            ComisionFrame.setVisible(false);
        }
    }//GEN-LAST:event_BoxOpcionActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AulaField;
    private javax.swing.JCheckBox BoxComision;
    private javax.swing.JCheckBox BoxOpcion;
    private javax.swing.JCheckBox BoxPiroO;
    private javax.swing.JCheckBox BoxPrioM;
    private javax.swing.JButton BtAtras;
    private javax.swing.JButton BtGuardar;
    private javax.swing.JInternalFrame ComisionFrame;
    private javax.swing.JTextField DiaField;
    private javax.swing.JTextField DiaFieldOp;
    private javax.swing.JTextField HoraFinField;
    private javax.swing.JTextField HoraFinFieldOp;
    private javax.swing.JTextField HoraInicioFIeld;
    private javax.swing.JTextField HoraInicioFieldOp;
    private javax.swing.JTextField LugarField;
    private javax.swing.JTextField MinutoFinField;
    private javax.swing.JTextField MinutoFinFieldOp;
    private javax.swing.JTextField MinutoInicioFIeldOp;
    private javax.swing.JTextField MinutoInicioField;
    private javax.swing.JTextField NumeroField;
    private javax.swing.JInternalFrame OpcionFrame;
    private javax.swing.JTextField ProfeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
