package IU;

import BaseDeDatos.BaseDeDatos;
import BaseDeDatos.Usuario;
import BaseDeDatos.EventoInterfaz;
import BaseDeDatos.Agenda;
import procesamiento.CreadorAgendas;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 * @author FedeSSD
 */
public class VistaPrincipal extends javax.swing.JFrame {
    /**
     * base de datos de trabajo
     */
    private BaseDeDatos baseDeDatos;
    /**
     * usuario seleccionado por la vista
     */
    private Usuario usuarioSeleccionado;


    // creacion de vistas
    VistaIngresar vistaIngresar;
    VistaAgregar vistaAgregar;
    VistaEventos vistaEventos;
    VistaAgendas vistaAgendas;
    VistaSeleccion vistaSeleccion;
    VistaVariante vistaVariante;
    private String nombreUsuario;

    public VistaPrincipal(BaseDeDatos baseDeDatos) {
        //asigno base
        this.baseDeDatos = baseDeDatos;

        //inicio los componentes
        initComponents();
        this.setLayout(new FlowLayout());
        this.vistaIngresar = new VistaIngresar(this);
        this.vistaAgregar = new VistaAgregar(this);
        this.vistaVariante = new VistaVariante(this);
        this.vistaEventos = new VistaEventos(this);
        this.vistaAgendas = new VistaAgendas(this);
        this.vistaSeleccion = new VistaSeleccion(this);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(false);
        this.add(vistaEventos);
        this.add(vistaAgendas);
        this.add(vistaSeleccion);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        labelMenu = new javax.swing.JLabel();
        labelGendat = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonCerrarSesion = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonImprimirAgenda = new javax.swing.JButton();
        botonGenerarAgendas = new javax.swing.JButton();
        botonAgregarEvento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 600));

        panelMenu.setToolTipText("");
        panelMenu.setName(""); // NOI18N
        panelMenu.setPreferredSize(new java.awt.Dimension(280, 280));

        labelMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMenu.setText("Menu Principal del Usuario:");

        labelGendat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelGendat.setText("Gendat");

        labelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUsuario.setText("nombreUsuario");

        jLabel1.setFont(new java.awt.Font("MV Boli", 3, 30)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("Agregar Evento");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel4.setText("Imprimir Agenda");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel5.setText("Eliminar Usuario");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel6.setText("Cerrar Sesion");

        botonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-lock-64.png"))); // NOI18N
        botonCerrarSesion.setMaximumSize(new java.awt.Dimension(140, 25));
        botonCerrarSesion.setMinimumSize(new java.awt.Dimension(140, 25));
        botonCerrarSesion.setPreferredSize(new java.awt.Dimension(140, 25));
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-denied-64.png"))); // NOI18N
        botonBorrar.setMaximumSize(new java.awt.Dimension(140, 25));
        botonBorrar.setMinimumSize(new java.awt.Dimension(140, 25));
        botonBorrar.setPreferredSize(new java.awt.Dimension(140, 25));
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonImprimirAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-image-64.png"))); // NOI18N
        botonImprimirAgenda.setMaximumSize(new java.awt.Dimension(140, 25));
        botonImprimirAgenda.setMinimumSize(new java.awt.Dimension(140, 25));
        botonImprimirAgenda.setPreferredSize(new java.awt.Dimension(140, 25));
        botonImprimirAgenda.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonImprimirAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirAgendaActionPerformed(evt);
            }
        });

        botonGenerarAgendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bookmark-64.png"))); // NOI18N
        botonGenerarAgendas.setMaximumSize(new java.awt.Dimension(140, 25));
        botonGenerarAgendas.setMinimumSize(new java.awt.Dimension(140, 25));
        botonGenerarAgendas.setPreferredSize(new java.awt.Dimension(140, 25));

        botonAgregarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-property-64.png"))); // NOI18N
        botonAgregarEvento.setMaximumSize(new java.awt.Dimension(140, 25));
        botonAgregarEvento.setMinimumSize(new java.awt.Dimension(140, 25));
        botonAgregarEvento.setPreferredSize(new java.awt.Dimension(140, 25));
        botonAgregarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarEventoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel3.setText("Generar Agendas");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMenuLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(labelGendat))
                            .addComponent(labelMenu, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUsuario))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(botonImprimirAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(botonGenerarAgendas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(botonAgregarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGendat)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(labelMenu))
                .addGap(15, 15, 15)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAgregarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGenerarAgendas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonImprimirAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(619, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //-------------ACCIONES DE BOTONES----------
    //******************************************

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        int input = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de querer cerrar sesion?", "Cerrar Sesion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        //input: 0=yes ; 1=no ; 2=cancel
        if (input == 0) {
            //dessuscribo observadores
            this.vistaAgendas.quitSujeto();
            this.vistaSeleccion.quitSujeto();

            this.setVisible(false);
            vistaIngresar.setVisible(true);
        }
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonAgregarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarEventoActionPerformed
        this.setVisible(false);
        vistaAgregar.setVisible(true);
    }//GEN-LAST:event_botonAgregarEventoActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int input = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro de querer eliminar el usuario " + nombreUsuario + "?", "Eliminar Usuario", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        //input: 0=yes ; 1=no ; 2=cancel
        if (input == 0) {
            this.setVisible(false);
            // borrar el usuario
            int index = getIndex();
            this.baseDeDatos.quitUsuario(this.nombreUsuario);
            this.vistaIngresar.quitElemento(index);

            vistaIngresar.setVisible(true);
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonImprimirAgendaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void botonGenerarAgendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirAgendaActionPerformed
        //genero agendas
        this.usuarioSeleccionado.generarAgendas();
    }//GEN-LAST:event_botonImprimirAgendaActionPerformed

    //-------------METODOS PARTICULARES---------
    //******************************************

    /**
     * @param nombreUsuario nombre de usuario
     * @return true en caso de poder agregarlo en la base de datos, false caso contrario
     * @brief trata de agregar usuario nuevo
     */
    public boolean setNuevoUsuario(String nombreUsuario) {
        //trata de agregar usuario
        boolean controlFlag = this.baseDeDatos.addUsuario(nombreUsuario);


        //en caso de setear correctamente el usuario
        return controlFlag;
    }


    /**
     * @brief actualiza sos labels eliminando un usuario
     */
    public int getIndex() {
        return this.baseDeDatos.getIndex(this.nombreUsuario);
    }

    /**
     * @param nombreUsuario nombre de usuario
     * @brief setter del nombre de usuario
     */
    public void setNombreUsuario(String nombreUsuario) {
        //setea el nombre de usuario en la label
        this.nombreUsuario = nombreUsuario;
        //sete el objeto usuario en su campo usuario
        this.usuarioSeleccionado = this.baseDeDatos.getUsuario(nombreUsuario);

        //actualiza la label
        this.updateSetLabelVista();
        this.updateEventos();
        this.updateAgendas();

        //setea el sujeto en los observadores
        this.vistaAgendas.setSujeto(this.baseDeDatos.getUsuario(nombreUsuario));
        this.vistaSeleccion.setSujeto(this.baseDeDatos.getUsuario(nombreUsuario));
    }

    /**
     * @brief actualiza sus labels
     */
    public void updateSetLabelVista() {
        labelUsuario.setText(nombreUsuario);
        //imprime todito el contenido
        this.baseDeDatos.toPrint();
    }

    public void updateEventos() {
        this.vistaEventos.vaciarLista();
        for (EventoInterfaz e : this.usuarioSeleccionado.getListaEventos()) {
            this.vistaEventos.agregarALista(e.getNombre());
        }
    }

    public void updateAgendas() {
        this.vistaAgendas.vaciarLista();
        this.vistaAgendas.actualizar();

    }

    /**
     * @param NombreEvento nombre del evento que quiero agregar
     * @brief agrego evento a la vista de la lista
     */
    public void agregarEventoLista(String NombreEvento) {
        vistaEventos.agregarALista(NombreEvento);
    }

    public Usuario getUsuarioSeleccionado() {
        return this.usuarioSeleccionado;
    }


    //-------------INTOCABLE-------------------
    //******************************************

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarEvento;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonGenerarAgendas;
    private javax.swing.JButton botonImprimirAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelGendat;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
